apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-k8s-cluster-metrics
  namespace: observability-backend
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.88.0
  mode: statefulset
  replicas: 3
  serviceAccount: otel-k8s-cluster-metrics-collector
  targetAllocator:
    enabled: true
    serviceAccount: otel-k8s-cluster-metrics-targetallocator
    allocationStrategy: "consistent-hashing"
    replicas: 2
    image: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:0.88.0
    prometheusCR:
      enabled: false
  env:
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  ports:
    - port: 8888
      protocol: TCP
      name: metrics
  config: |
    receivers:
      kubeletstats:
        collection_interval: 20s
        auth_type: "serviceAccount"
        endpoint: "${env:K8S_NODE_NAME}:10250"
      k8s_cluster:
        auth_type: serviceAccount
        node_conditions_to_report:
          - Ready
          - MemoryPressure
        allocatable_types_to_report:
          - cpu
          - memory
      prometheus:
        config:
          scrape_configs:
          - job_name: apiserver
            authorization:
              credentials_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"
              type: Bearer
            honor_labels: true
            honor_timestamps: true
            kubernetes_sd_configs:
            - follow_redirects: true
              kubeconfig_file: ''
              role: endpoints
            metrics_path: "/metrics"
            follow_redirects: true
            relabel_configs:
            - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
              separator: ;
              regex: default;kubernetes;https
              replacement: $$1
              action: keep
            scheme: https
            scrape_interval: 20s
            scrape_timeout: 10s
            tls_config:
              ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
              insecure_skip_verify: true
        target_allocator:
          endpoint: http://otel-prom-k8s-metrics-targetallocator:80
          interval: 30s
          collector_id: ${POD_NAME}
          http_sd_config:
            refresh_interval: 60s
    
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 10

    exporters:
      logging:
        loglevel: debug
      prometheusremotewrite:
        endpoint: "http://prometheus.observability-backend.svc.cluster.local:80/api/v1/write"
        resource_to_telemetry_conversion:
          enabled: true
    service:
      pipelines:
        metrics:
          receivers: [prometheus, kubeletstats, k8s_cluster]
          processors: [memory_limiter, batch]
          exporters: [logging, prometheusremotewrite]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-k8s-cluster-metrics-collector
rules:
  - apiGroups:
      - ''
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/proxy
      - nodes/spec
      - nodes/stats
      - nodes/metrics
      - services
      - endpoints
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - pods
      - pods/status
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups: 
      - "monitoring.coreos.com"
    resources:
      - servicemonitors
      - podmonitors
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
      - daemonsets
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups: 
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-k8s-cluster-metrics-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-k8s-cluster-metrics-collector
subjects:
  - kind: ServiceAccount
    # quirk of the Operator
    name: otel-k8s-cluster-metrics-collector
    namespace: observability-backend
  - kind: ServiceAccount
    name: otel-k8s-cluster-metrics-targetallocator
    namespace: observability-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-k8s-cluster-metrics-collector
  namespace: observability-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-k8s-cluster-metrics-targetallocator
  namespace: observability-backend
